export interface insertClientDTO {
    name: string,
    id_MercadoLivre: string,
    email: string,
    CPF: string,
    telephone: string,
    CEP: string,
    address: string,
    number: string,
    complemento: string,
    bairro: string,
    city: string,
}
export interface insertClientDTI {
    id: string, 
    name: string,
    id_MercadoLivre: string,
    email: string,
    CPF: string,
    telephone: string,
    CEP: string,
    address: string,
    number: string,
    complemento: string,
    bairro: string,
    city: string,
    status: number, 
    date_Status: Date,
    id_User: string, 
    date_Create: Date,
    date_Update: Date,
}